services:
  php:
    build: docker/php
    networks:
      - interlope
    expose:
      - "9000"
    volumes:
      - ./app:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8069:80"
    networks:
      - interlope
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    healthcheck:
      test:
        ["CMD-SHELL", "curl -so /dev/null http://localhost/ || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:alpine
    user: postgres
    expose:
      - "5432"
    ports:
      - "5469:5432"
    environment:
      - POSTGRES_PASSWORD=kulcs
      - POSTGRES_USER=interlope
      - POSTGRES_DB=interlope
      - TZ=America/Sao_Paulo
      - PGTZ=GMT-3
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - interlope
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interlope"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  postgres:

networks:
  interlope:
    name: interlope
    driver: bridge
    ipam:
      config:
        - subnet: "172.69.0.0/16"
